# This tests selecting multiple resources in a namespace,
# and only applying to a subset of clusters.
# Prerequisite:
# Run `kubectl apply -f rp-ns.yaml` in this directory to create the test namespace.
# The deployment, and service are all defined below.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx
  namespace: test-ns
  labels:
    app: test-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-nginx
  template:
    metadata:
      labels:
        app: test-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: test-nginx
  namespace: test-ns
  labels:
    app: test-nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: test-nginx
---
apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ResourcePlacement
metadata:
  name: rp-nginx
  namespace: test-ns
spec:
  resourceSelectors:
    - group: apps
      kind: Deployment
      name: test-nginx
      version: v1
    - group: ""
      kind: Service
      name: test-nginx
      version: v1
  policy:
    placementType: PickN
    numberOfClusters: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
